name: dermai
description: DermAI — AI-powered skin disease screening (mobile client)
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  image_picker: ^1.1.0
  shared_preferences: ^2.2.2
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
